-- The aggregator feed: one row per external headline, written by the
-- GitHub job (scripts/news_feed.py, service role) and read by /news (anon).
-- No article bodies are stored — a headline, a one-line summary where the
-- source gives one, and the link out. Rows older than 60 days are pruned by
-- the job.
create table if not exists public.news_feed (
  id           bigint generated by default as identity primary key,
  url          text not null unique,
  source       text not null,               -- 'isc' | 'alsumaria' | 'rs' | 'cbi' | 'almada'
  title        text not null,
  summary      text,
  lang         text not null default 'ar',
  ticker       text,                        -- ISC announcements name a company
  published_at timestamptz not null,
  seen_at      timestamptz not null default now()
);
create index if not exists news_feed_published_idx on public.news_feed (published_at desc);
alter table public.news_feed enable row level security;
drop policy if exists news_feed_read on public.news_feed;
create policy news_feed_read on public.news_feed for select to anon, authenticated using (true);
grant select on public.news_feed to anon, authenticated;
